Service-Static:
  port: 4605
  root: /Volumes/External/DATA
  blocklist:
    - /512picture ---
    # - /512picture/FY3D_MERSI_T000_L2_PAD_MLT_GLL_20200223_POAD_0250M_MS_03_02_01.JPG ---
    # - /test 123 ---
  allowlist:
    # - /512picture ---
    # - /512picture/FY3D_MERSI_T000_L2_PAD_MLT_GLL_20200223_POAD_0250M_MS_03_02_01.JPG ---
    # - /test\ 123 ---