module.exports = mimeType

function mimeType (ext) {
  switch (ext) {
    case '.tif':
      return 'image/tiff'
    case '.png':
      return 'image/png'
    case '.jpg':
      return 'image/jpeg'
    case '.ico':
      return 'image/x-icon'
    case '.kml':
      return 'application/vnd.google-earth.kml+xml'
    case '.zip':
      return 'application/zip'
    case '.evy':
      return 'application/envoy'
    case '.fif':
      return 'application/fractals'
    case '.spl':
      return 'application/futuresplash'
    case '.hta':
      return 'application/hta'
    case '.acx':
      return 'application/internet-property-stream'
    case '.hqx':
      return 'application/mac-binhex40'
    case '.doc':
      return 'application/msword'
    case '.dot':
      return 'application/msword'
    case '.oda':
      return 'application/oda'
    case '.axs':
      return 'application/olescript'
    case '.pdf':
      return 'application/pdf'
    case '.prf':
      return 'application/pics-rules'
    case '.p10':
      return 'application/pkcs10'
    case '.crl':
      return 'application/pkix-crl'
    case '.ai':
      return 'application/postscript'
    case '.eps':
      return 'application/postscript'
    case '.ps':
      return 'application/postscript'
    case '.rtf':
      return 'application/rtf'
    case '.setpay':
      return 'application/set-payment-initiation'
    case '.setreg':
      return 'application/set-registration-initiation'
    case '.xla':
      return 'application/vnd.ms-excel'
    case '.xlc':
      return 'application/vnd.ms-excel'
    case '.xlm':
      return 'application/vnd.ms-excel'
    case '.xls':
      return 'application/vnd.ms-excel'
    case '.xlt':
      return 'application/vnd.ms-excel'
    case '.xlw':
      return 'application/vnd.ms-excel'
    case '.msg':
      return 'application/vnd.ms-outlook'
    case '.sst':
      return 'application/vnd.ms-pkicertstore'
    case '.cat':
      return 'application/vnd.ms-pkiseccat'
    case '.stl':
      return 'application/vnd.ms-pkistl'
    case '.pot':
      return 'application/vnd.ms-powerpoint'
    case '.pps':
      return 'application/vnd.ms-powerpoint'
    case '.ppt':
      return 'application/vnd.ms-powerpoint'
    case '.mpp':
      return 'application/vnd.ms-project'
    case '.wcm':
      return 'application/vnd.ms-works'
    case '.wdb':
      return 'application/vnd.ms-works'
    case '.wks':
      return 'application/vnd.ms-works'
    case '.hlp':
      return 'application/winhlp'
    case '.bcpio':
      return 'application/x-bcpio'
    case '.cdf':
      return 'application/x-cdf'
    case '.z':
      return 'application/x-compress'
    case '.tgz':
      return 'application/x-compressed'
    case '.cpio':
      return 'application/x-cpio'
    case '.csh':
      return 'application/x-csh'
    case '.dcr':
      return 'application/x-director'
    case '.dir':
      return 'application/x-director'
    case '.dxr':
      return 'application/x-director'
    case '.dvi':
      return 'application/x-dvi'
    case '.gtar':
      return 'application/x-gtar'
    case '.gz':
      return 'application/x-gzip'
    case '.hdf':
      return 'application/x-hdf'
    case '.ins':
      return 'application/x-internet-signup'
    case '.isp':
      return 'application/x-internet-signup'
    case '.iii':
      return 'application/x-iphone'
    case '.js':
      return 'application/x-javascript'
    case '.latex':
      return 'application/x-latex'
    case '.mdb':
      return 'application/x-msaccess'
    case '.crd':
      return 'application/x-mscardfile'
    case '.clp':
      return 'application/x-msclip'
    case '.dll':
      return 'application/x-msdownload'
    case '.m13':
      return 'application/x-msmediaview'
    case '.m14':
      return 'application/x-msmediaview'
    case '.mvb':
      return 'application/x-msmediaview'
    case '.wmf':
      return 'application/x-msmetafile'
    case '.mny':
      return 'application/x-msmoney'
    case '.pub':
      return 'application/x-mspublisher'
    case '.scd':
      return 'application/x-msschedule'
    case '.trm':
      return 'application/x-msterminal'
    case '.wri':
      return 'application/x-mswrite'
    // case '.cdf':
    //   return 'application/x-netcdf'
    case '.nc':
      return 'application/x-netcdf'
    case '.pma':
      return 'application/x-perfmon'
    case '.pmc':
      return 'application/x-perfmon'
    case '.pml':
      return 'application/x-perfmon'
    case '.pmr':
      return 'application/x-perfmon'
    case '.pmw':
      return 'application/x-perfmon'
    case '.p12':
      return 'application/x-pkcs12'
    case '.pfx':
      return 'application/x-pkcs12'
    case '.p7b':
      return 'application/x-pkcs7-certificates'
    case '.spc':
      return 'application/x-pkcs7-certificates'
    case '.p7r':
      return 'application/x-pkcs7-certreqresp'
    case '.p7c':
      return 'application/x-pkcs7-mime'
    case '.p7m':
      return 'application/x-pkcs7-mime'
    case '.p7s':
      return 'application/x-pkcs7-signature'
    default:
      return 'application/octet-stream'
  }
}
